[tool.poetry]
name = "brewblox-plaato"
version = "0.1.0"
description = "Brewblox service for the Plaato airlock"
authors = ["BrewPi <development@brewpi.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<4"
brewblox-service = "^0.33.0"

[tool.poetry.dev-dependencies]
aresponses = "^2.1.4"
pytest-flake8 = "^1.0.7"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
pytest-aiohttp = "^0.3.0"
flake8 = "^3.9.2"
autopep8 = "^1.5.7"
pytest = "^6.2.4"
flake8-quotes = "^3.2.0"
asyncmock = "^0.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
